name: PullRequest

on:
  pull_request:
    types: [opened,reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Echo
        run: yarn build
