name: Merge Master

on:
  workflow_dispatch:
  pull_request:
    types: [closed]

jobs:
  build:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Merge
        # if: ${{ github.base_ref == 'master' }}
        run: |
          git fetch
          git checkout master
          git pull
          git log --oneline
          # git config --global user.email "messiasleonardo98@gmail.com"
          # git config --global user.name "LeonardoMessias98"
          # git fetch
          # git checkout master
          # git pull origin master
          # git checkout develop
          # git merge origin/master
          # git push origin develop
