name: Merge Master

on:
  workflow_dispatch:
  pull_request:
    types: [closed]

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Merge
        if: ${{ github.base_ref == 'master' }}
        run: |
          git fetch
          git checkout develop
          git config --global user.email "messiasleonardo98@gmail.com"
          git config --global user.name "LeonardoMessias98"
          git merge -Xignore-space-change origin/master --allow-unrelated-histories
          git push origin develop
