name: "other_schedule"
on:
  schedule:
  - cron: "*/1 * * * 1-5"
  
  workflow_dispatch:
 
jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Echo some text
      run: |
        curl -X POST --data-urlencode "payload={\"channel\": \"#squad-posto-ipiranga\", \"username\": \"webhookbot\", \"text\": \"Teste integração GITHUB actions.\", \"icon_emoji\": \":ghost:\"}" https://hooks.slack.com/services/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
