name: "other_schedule"
on:
  schedule:
  - cron: "*/1 * * * 1-5"
jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Echo some text
      run: echo teste
