name: "schedule"
on:
  schedule:
    - cron:  '*/5 * * * *'    # At every 15th minute

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Every time
        run: echo "This step will always run"

